appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: HizZNPtLVAvMT87I/ADstiP5Lh6FLXebFfl5jW7xbyt6/8gStZt5YQXMgwyLCWtB/lHY4/rWQds0VmzlE5F95fNbfCNxdbAdG3cjiBPIRNaS4WR1MFT0SNCoZCyoth3dXeomKIjqBWYAW6hsbEQORybC9s+swUyN5plnYswpjrRSwJuNEAiD+gDpzn2rXrGAEGEkssTid/CBePQwb6vSHBUjwzMiwV7ILiLVXFBBJ7rP1Xrww2l/mP9Svwdwty0rxSyeBrsivanG4edkLXp+QkVhohi1qP219Vvk3MEYmcYZZLndryMvkNE8noWbStnH8ZPp7rnvpV+MFaV6sRtrcLl8Tov+SnuZwfWhW8h7GRZSQxRHmhC0PqTUHiaQZEDzYxnBTO1jiTmD/wXuAID0pbyZScXSQvmKw3vr2qMzw8lHeVnfk4ZbTDrW1ci5ygqEtq/nveaZjDTNe+/lH54Y1wHC/Zg5D5evZETKdw3tDzRch9f/JMHodAxrPSEVpMSlGYkMi8nbJrB1d0iPUPqF4jtX0eJePeRhIbV7amsP9wYLrtEzOSqpIEIBfYK8E2+iM8/vTs1/4X8YeYAJm2b8jfwDuRJaRsjIvtEXhg5GyNd0drY6a4nySYc6b5TVXk+f3SnAXvM8SAfRCxyN8K3daMmrIqqvJD8ic3Czy25aRVg=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: false
